## Deliverable 3. Create a Travel Itinerary Map.

In [58]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [59]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
# vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
# vacation_df.head()
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Tura,IN,75.18,clear sky,25.5198,90.2201,Hotel RIKMAN Continental
1,3,Kapaa,US,78.80,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
2,7,Rio Grande,BR,71.01,light rain,-32.0350,-52.0986,Hotel Atlântico Rio Grande
3,8,Kaputa,ZM,66.88,overcast clouds,-8.4689,29.6619,Chelelwa Charlets
4,9,Shiyan,CN,70.00,clear sky,32.6475,110.7781,Fenghuang Garden Holiday Hotel
5,12,Bambous Virieux,MU,77.00,broken clouds,-20.3428,57.7575,Casa Tia Villa
6,13,Rikitea,PF,79.48,clear sky,-23.1203,-134.9692,Pension Maro'i
7,18,Hambantota,LK,75.20,broken clouds,6.1241,81.1185,Bungalow 63
8,22,San Juan,AR,65.41,clear sky,-31.5375,-68.5364,Hotel Provincial
9,23,Carnarvon,AU,78.80,clear sky,-24.8667,113.6333,Hospitality Carnarvon

In [60]:
vacation_df.tail()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
637,1838,Kindu,CD,69.91,overcast clouds,-2.9500,25.9500,Résidence Okanda
638,1840,Wote,KE,66.72,overcast clouds,-1.7808,37.6288,Midways Hotel
639,1842,Itapetinga,BR,68.16,clear sky,-15.2489,-40.2478,Hotel Del Rey
640,1843,Kibiti,TZ,73.33,overcast clouds,-7.7218,38.9375,Experia Guest House
641,1844,Hirekerur,IN,72.93,broken clouds,14.4667,75.3833,Shivali Lodge

In [61]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]
# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [62]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [63]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == "Batemans Bay"]
vacation_end = vacation_df.loc[vacation_df['City'] == "Ulladulla"]
vacation_stop1 = vacation_df.loc[vacation_df['City'] == "Flinders"]
vacation_stop2 = vacation_df.loc[vacation_df['City'] == "Charlestown"] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == "Nelson Bay"]

In [64]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start['Lat'].to_numpy()[0], vacation_start['Lng'].to_numpy()[0]
end = vacation_end['Lat'].to_numpy()[0], vacation_end['Lng'].to_numpy()[0]
stop1 = vacation_stop1['Lat'].to_numpy()[0], vacation_stop1['Lng'].to_numpy()[0]
stop2 = vacation_stop2['Lat'].to_numpy()[0], vacation_stop2['Lng'].to_numpy()[0]
stop3 = vacation_stop3['Lat'].to_numpy()[0], vacation_stop3['Lng'].to_numpy()[0]

In [77]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
au_bike_trip = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='BICYCLING')
fig.add_layer(au_bike_trip)
fig

Figure(layout=FigureLayout(height='420px'))

In [70]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,886,Batemans Bay,AU,69.01,few clouds,-35.7167,150.1833,Batemans Bay Marina Resort
1,741,Ulladulla,AU,70.00,broken clouds,-35.3500,150.4667,Sandpiper Motel
2,315,Flinders,AU,73.99,clear sky,-34.5833,150.8552,Shellharbour Resort & Conference Centre
3,146,Charlestown,AU,78.01,clear sky,-32.9500,151.6667,Panorama Motor Inn Hotel
4,1565,Nelson Bay,AU,75.99,clear sky,-32.7167,152.1500,Mantra Nelson Bay

In [74]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [75]:
## 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))